#!/usr/local/bin/php

<?php 
require("/home/content/48/7686848/html/includes/bv-library.php");

printHeader("Metaparadigm or Theory of Everything? Reality Begins With Consciousness"); 
?>
<br /><br />
<H1 CLASS="title">
Paradigms, Metaparadigms and Theories of Everything in TDVP.</H1>
<br /><br />
As it can be applied to all the major areas of scientific endeavor, we describe TDVP as a "metaparadigm" because of its overriding higher-level basis. This paradigmatic model is not intended to solve all current unexplained mysteries in physics or any other endeavor relating to content. But, we have yet to find an area of principles of reality that cannot be expressed within this global paradigmatic shift. There are, of course, millions of, thus far, insoluble questions and unknowns in the world, but we're attempting broad models that are not being refuted, not to provide omniscience! TDVP is a practical, so-called "Theory of Everything" (TOE): We intently dislike the term "TOE", but because it's been commonly and persistently used, we need to apply it, at times, to compare TDVP with other proposed "TOE" models. TOE is an unfortunate term because it may be interpreted ambiguously. In its most appropriate sense, "TOE" implies a universal feasibility model applicable at every level of endeavor. But in its misinterpreted, inappropriate meaning, TOE is mistakenly regarded as representing theories of all-embracing knowledge. No model, except a proposed Divinity, is all-embracing in answering everything. Although TDVP is sometimes called a Theory of Everything, we do not like the term because it is ambiguous. TDVP was not meant to be a TOE in the sense that physics has sought a TOE describing all of physics in a few equations as Einstein sought and so many others. We use the terms "TOE" and "paradigm" not to explain bizarre neutrino behaviors, mixing angles amongst quarks, every detailed change in evolution, the exact DNA sequence, or specific chemistry: Whereas these are all legitimate areas to clarify, they reflect content questions, not paradigms. Paradigms are not just theoretical, they are practical but predominantly examine process not content, broader pictures and principles, not specifics. But by virtue of the process, they could assist with appreciation of the content and the specifics--that would be the secondary application.
<br /><br />
Ironically, in TDVP, we attempt a very broad scientifically empirical, inferential model based on specific testable or hypothetical content data, but that is directed towards the process of testing the model. Additionally, if possible, deductive mathematics and logic provide demonstrable support. Moreover, existing current solid empirical data can frequently be incorporated into the model by applying the principles of the "philosophy of science"; and even esoteric abstractions of process still have content applications.
<br /><br />
"TDVP is a model in evolution: We do not have answers for everything. We're not even close. There are key elements that may not be soluble at any point in the future. The vast limitations of proof in biology and psychological sciences will not change. They are based on inductive reason, an order of magnitude less certain than the physical sciences, which already are embedded in controversy. Much more needs to be done, and even then we can never approach omniscience. The biological sciences and even more the psychological databases are simply too tenuous to draw many conclusions, even in areas that have been studied for decades. Inductive empirical proofs are simply at a different level from the physical sciences, and even physics relies on inductive empiricism. We can never achieve complete proof by even proving falsifiable scientific data, because the inductive elements limit proof and we ultimately rely on less certainty than interpretations. Moreover, in TDVP, certain models are even more esoteric and less subject to proof: How do we show that "life" always exists, as opposed to times when there is no life /no existence? We can make conceptual jumps and posit new secondary ideas, such as infinity, and this leads to tertiary hypotheses such as infinite life. And even despite enormous progress in applying TDVP to the mathematicological models, we have not yet, and likely will never prove each and every secondary and tertiary component of TDVP." 
<br /><br />
<b>For clarity, we divide this metaparadigmatic model into six statements:</b><br /> 
i. Reality involves a unified wholeness of the continuous infinite subreality with the infinite bidirectionally pervading the discrete finite subreality experience at every dimensional level.
<br /><br />
ii. The continuous, infinite subreality reflects all of time and space in totality simultaneously (and therefore, on a finite level appears "nonlocal") and exists as a subreality essence (a metareality) involving a pervasive consciousness (information expressed through meaning as metaconsciousness) and multidimensional order (extropy) with potential life --"polife"--which then manifests as physical life in our current experiential specific finite domain (3 dimensions of space and one moment in time: "3S-1t") when linked with the correct current physiology.
<br /><br />
iii. The discrete, finite, natural law based cosmic subreality component is fundamentally inseparably tethered from its origin as a triad of space--time--broader "consciousness" (S, T and C-substrates--CST). This tethering then separates and manifests across, between and within multiple fluctuating dimensions ("indivension") in "individual-units". This allows a merging of zillions of individual-unit realities and yet retains a profound potential communication with the tethered CST components. Individual-units may reflect individual humans or any other individual sentient beings. Importantly, individual units can also reflect groups, families, societies, cultures, ethnic groups or any other living population. They may also reflect any inanimate (not living) components of the finite S, T or C substrates.
<br /><br />
iv. Our experience of the commonly interpreted physical domain (3S-1t) is profoundly limited by subjective perception, conception and common experience. In humans, the endpoint expression of such a finite-infinite interface is the brain, and the brain can filter, integrate or manifest meaning through neurological consciousness (N-consciousness). N-consciousness (N-C) can be clear, or in various states of altered or impaired consciousness. There is a technicality here, implying that because of the "consciousness" element, at minimum, any sentient being is dealing with 3S-1t-1C because there is a dimension of conscious meaning that is fundamentally linked with S and T. And if we describe 1C, then it is technically more consistent to describe N-C as there is no restriction in our experience to 1 dimension of consciousness and therefore, it is 3S-1t-NC even in our regular human experience. This Neurological Consciousness expressed through the brain becomes the final common pathway for Psychological Consciousness as well as the broader metaconsciousness (which may include qualities like love, honor, courage or even negatives such as hatred). 
<br /><br />
v. The combined finite-infinite reality is always relative. It is relative to any subjective realities experienced by any level of individual-units. At the broadest level, it can be conceptualized from the "top-down", in terms of transfinite higher dimensions influencing dimensions below. Alternatively, it can be also be experienced "bottom-up" beginning at the information and meaning that we have in the few pieces of our 3S-1t jigsaw puzzle, and trying to conceptualize or distinguish dimensions of time and consciousness that are difficult to perceive or conceptualize. The bottoms-up approach, necessarily prevalent in most human thought, is much more limiting and so it makes it more difficult to think out of the box, which results in not conceptualizing "higher dimensions". In contrast, the top-down approach, which pervades the infinite subreality, as well as the transfinite, would imply appreciation of the greater picture. (Theologically, some may conceive of a "higher power" and mathematically, this can be conceptualized through "dimensionometry" and "dimensional extrapolation". 
<br /><br />
vi. The philosophical portrayal of TDVP is best described by a new term, "Unified Monism".
<br /><br />
<script type="text/javascript">
<!--
window.onload=openmenu('menu0');
//-->
</script>
<?php printFooter(); ?> 
