#!/usr/local/bin/php

<?php 
require("/home/content/48/7686848/html/includes/bv-library.php");

printHeader("AUTHOR'S PREFACE (Dr. Vernon M. Neppe)"); 
?>
<br /><br />
<H1 CLASS="title">AUTHOR'S PREFACE (Dr. Vernon M. Neppe)</H1>
<em>Reality Begins With Consciousness: A paradigm shift that works</em></H2>
<br /><br />
<center><h2>"The more I learn the less I learn I know." Vernon M Neppe, circa 1967</h2></center>
<br><br>

<img src="/images/neppe_thumb.jpg" align="left">Since my childhood, I had contemplated the contradictions in our current scientific model-- a model that I, nevertheless, realized worked very well in possibly 99.99% of cases. Yet I had wondered why these possibly 0.01% of apparent aberrations occurred. Over two decades, I gradually concluded that a new model could explain some of these problems: If an imaginary observer existed outside the "box" of our current reality, his relative position imagining the situation would be different. He would be able to observe far more of our current reality looking from the outside and then examining inward. This would imply that the number of dimensions could repetitively increase because the observer could look at that new reality from the outside, and this could continue ad infinitum. Effectively, I began to use this outside-in approach to examine ostensibly anomalous information. I applied it to many disciplines, and it seemed workable, too, across the sciences I examined.
<br /><br />
I became convinced that this experience was relative to one's location. I penned notes about this, studied the existing data, and gradually by the mid-1980s, after many years of contemplation, had refined this to whether there was some kind of essence. I wondered about the essential core in our existence, whether it was always expressed in space and time in other dimensions, and whether we could be living in an N-dimensional reality, as part of a broader infinite existence. I realized we were only perceiving a tiny fraction in our conventional three spatial dimensions and one moment in time--our present experiential reality. 
<br /><br />
In addition, I realized there needed to be a content and that the fundamental spatial elements could be expressed not in the rectilinear box noted by the observer, but in increasingly complex curved movements. I was struck by the ubiquity in all of nature of these vortical shapes. I wondered whether these three-dimensional spatial rotating objects--vortices--could be playing a role that was completely fundamental even in this multidimensional world that I was contemplating. I opposed myself: My rational mind argued that even contemplation of vortices was too ridiculous a concept to embrace. Yet the more I looked, the more this idea became feasible: Vortices and curved objects were ubiquitous in nature and they fitted the theoretical need I had conceptualized. Somehow, there had to be a content by which any kind of individual, society, or even humankind in general, or any group or any other level of individuals, or even other sentient beings, could interact. This was a function of social interaction and reflected a consistent combined reality. Vortices could fit this role because they were dynamically changing in state reflecting movements from moment to moment, and yet they also reflected a consistent trait over time where others would be objectifying in a relative sense their realities with others. Vortices could be interacting and interfacing and there could theoretically be "zillions"   of such combinations taking place with much of reality being silent as they would not be expressing themselves in consciousness. 
<br /><br />
Moreover, there was no need for these dynamic forms to be full-blown classical vortices. Any moving curvature element would fulfill that role and provide a content for this interacting process (which many years later in our model we called "indivension"). Certainly, curved movement was easier to conceive of than rectangular ones because they were more natural and would not be as restricted to Euclidean space.
<br /><br />
And so, in my initial model, first, there was N-dimensionality, with this outside-in derivation from an essence and an observational consciousness, and there was also an inside-outside approach. Then there was the role of an (infinite) essence and an N- dimensional reality. But, then even to contemplate vortices-- quite ridiculous surely? Yet, the idea persisted. 
<br /><br />
I gradually put this together into a model I called the concept vortex pluralism. I presented this as an invited lecture to a sub-branch of the American Philosophical Association  , and I was surprised at the response. Instead of ridicule--after all I was not a philosopher and what did I know anyway?--it met with a standing ovation. I felt at the time that given N-dimensionality, this was pluralistic, not monistic or dualistic, and so I described my model as "pluralism". It was going to be published in a book, but the editor justifiably objected to the lack of references. And that was true: It was my own idea that had spontaneously taken hold, and at that point, there were, strangely, no formal references yet. I revised this paper and placed it onto the Internet. And I added hundreds of references, discovering in retrospect, that, indeed, there was a theoretical justification for what I was positing. Later and more appropriately, I called the model "vortex N-dimensionalism" because I realized this model was not based on plural realities just N-dimensions, and that this reflected one unified reality. 
<br /><br />
I realized, too, that despite the fundamental laws of thermodynamics  , living beings also exhibited order not disorder, and was puzzled why life came about. So, already at that point, I was puzzling over finity and infinity, N-dimensionality, vortices, multidimensional space-time, observer consciousness outside our usual space-time, life, the role of order and the variable directional approach (outside-in and also inside out--later on we referred to this as the top-down and bottom-up approach). I produced a two-part document of some eighty pages, and circulated it to a few colleagues. I was stimulated to action when an anonymous colleague overseas justifiably critiqued my then life's work: "But how can he test this? And where is the proof?" I understood this criticism, and agreed with it, because I knew he was correct: And it was this extreme prod that provoked my need to work with a mathematician and a physicist and re-look at this paradigm. 
<br /><br />
Through the International Society for Philosophical Inquiry, I met Dr. Edward Close who had written the book Transcendental Physics. This book had many similar fundamental ideas to vortex N-dimensionalism. We made an interesting team: I as a consciousness researcher, neuroscientist and psychiatrist, who could play the role of ignorant creative thinker in physics and mathematics, and on the other hand, Dr. Close as a physicist and a mathematician, par excellence, who could, similarly, bounce off creative ideas in the biological, consciousness and social sciences. 
<br /><br />
I spent the next year immersed in complex physics and advanced mathematics because I realized I would need to apply sufficient skills to use logic and think creatively in these disciplines. 
<br /><br />
We were ready, and both of us recognized this was our song we needed to sing. It was a project that we were driven to complete: It was our gift, however, small and possibly even misguided, to humankind. The result are these books: Reality begins with Consciousness: A Paradigm Shift that Works and the companion book, Space, Time and Consciousness: The Tethered Triad. 
<br /><br />
Having spent months allowing colleagues around the world to critique over twenty major revisions of this model, we've become increasingly persuaded that our model is fundamentally truer than any other that currently exists: Often models die after six months of scientific, mathematical and creative critiques. Yet, we've been able to answer challenges, and though the fundamental metaparadigm remains, the emphasis on certain areas, such as infinity, order, life, meaning, time, consciousness, tethering, vortices and dimensionality has been amplified--and concepts and definitions have been clarified. Every query has been seriously addressed, appropriately answered, and, we believe, adequately encompassed within our model. We are grateful that the clarifications required made the model stronger and allowed it to grow, both in being more coherent, as well as more detailed, in its essentials. We are encouraged, too, by the support for the underlying hypotheses and the fundamental metaparadigm and the acclaim by responding scientists: This continued growth of a model would be expected for any consistent and feasible paradigmatic shift.
<br /><br />
Has our model succeeded? For a paradigm to work, the underlying axioms should feasibly, without contradiction or demonstrable falsification, explain empirical data and be supported through mathematicologic approaches. Our model, now called the Triadic Dimensional-Distinction Vortical Paradigm model (TDVP), does just that, and, of course, is applicable across many scientific disciplines (physics, life, consciousness and psychological sciences) and mathematically is logically justified. 
<br /><br />
Yet, how dare we postulate a paradigm shift that cuts into the sheer fabric of current reductionistic materialism? And moreover, how dare we involve multidimensionality, consciousness, infinity, life and order? It's like suggesting the flat world is round, surely?
<br /><br />
We have to agree, at this point, with expert reviewers who believe that TDVP will endure and will become critically important for a long, long time to come. Yet Dr. Close and I both still anticipate the initial resistance, anger, denial, and even ridicule. This may not be surprising because TDVP literally shatters many prevailing ideas about the very nature of reality, and it furthermore, has both the mathematics and the empiricism to demonstrate its viability, with hypotheses that are not yet tested. Our TDVP model has emphasized the cardinal role of consciousness and the need for a specific kind of higher dimensionality. And it has addressed infinity, order and life, and restructuring of time as necessities. Based on empirical data, potential proofs of our metaparadigm, mathematical justifications, and qualitative tabulations, we have justified it as the most complete Theory of Everything and extensive practical paradigm ever posited. 
<br /><br />
Our first book, Reality Begins with Consciousness, is written to be more easily read. It is still formidable, but those not reading all of it will obtain the fundamentals, without the data and amplifications, at the start. This book on TDVP begins with a 10-point summary of the basics of the TDVP model, then the key single statement, then jumps to 100 core points. It then deals with fundamentals and gradually builds up, in some detail, to why the key metaparadigm fits. It progresses as if one were doing a university course in the area, with basics, and then with increasing complexity of some areas.
<br /><br />
The second companion book, Space, Time and Consciousness: The Tethered Triad, relates to amplifications, specialized models and speculation. Here are the challenges, speculations and proposals for future research. This book incorporates some remarkable ideas, and is more complex than the first book. It's almost like one is then studying a further advanced course. But in both books, our frequent headers and subheaders allow greater readability and the opportunity to skip certain areas, or to come back to them later. 
<br /><br />
We look at it simply as delivering two ostensibly cutting edge books. This is the first, and I postulate that both will impact the ideas of all of our readers. Those embroiled in reductionistic materialism may be challenged to modify their views because they appear unjustifiable in the light of the empirical data presented, and our ideas demonstrate the contradictions to our standard, current physical paradigm.
<br /><br />
We hope that this book will fulfill the initial reviewers' impressions that Reality Begins with Consciousness will have long-lasting major impacts on the physical, biological, consciousness, psychological and mathematical sciences. Certainly, the concept of an enduring model of reality that provides a workable paradigm shift across all the scientific disciplines, and has mathematical theorems and proofs, is very important. Add to this, a paradigm that provides a new philosophical perspective and yet still is consonant with philosophy including mysticism and its potential enduring relevance is enhanced. Whether it fulfills this promise remains to be seen. But, we, the authors, interpret this as far the most important life's contribution of our lives.
<br /><br />
<h2>Vernon M Neppe MD, PhD, FRSSAf, DFAPA, BN&NP, FFPsych, MMed, DPsM, DSPE.<br />
Seattle, WA, USA.</h2>
<br /><br />
<h2>Post-script: 2nd Edition addition to Dr Neppe's Preface</h2> 
An important caution, however, needs to be emphasized: Clearly, there is a great deal more to be done. We have only a tiny knowledge base of what exists. Complex aspects of physics are disputed. How much more so are the biological, consciousness and psychological findings where our "proofs" are limited? In these scientific disciplines, we can only apply conclusions using, at best, tenuous inductive reasoning based on experimental data. This is often an order of magnitude below those same controversial but very complex "proofs" in physics.
<br /><br /> 
We can certainly argue that the data we cite is not contradicted because it has not been falsified. Furthermore, that the data appears to occur and be feasible in the collective experience of our society. But we recognize that feasibility has its own limitations.
<br /><br /> 
Our application of the TDVP model as a metaparadigm is ambitious and often based on the feasibility of fundamental aspects, yet it only provides principles and process for examination of the content, namely the data. And based on the comparative metrics of Table 5, it may provide this extremely effectively. However, that does not mean that this is truly how reality works: This book may at best provide a good start to explain our model which we perceive as feasible and to stimulate ideas, research and thinking for others.
<br /><br /> 


<script type="text/javascript">
<!--
window.onload=openmenu('menu0');
//-->
</script>
<?php printFooter(); ?> 
